// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'teacher_account.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'teacher_account.g.dart';

@freezed
class TeacherAccount with _$TeacherAccount {
  const factory TeacherAccount({
    required int id,
    required String name,
    required String email,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
  }) = _TeacherAccount;

factory TeacherAccount.fromJson(Map<String, dynamic> json) => _$TeacherAccountFromJson(json);
}